INSERT INTO DECATH_STORE(STORE_ID,STORE_NAME,STORE_CITY) VALUES(100,'DEC-1','BTM');
INSERT INTO DECATH_STORE(STORE_ID,STORE_NAME,STORE_CITY) VALUES(101,'DEC-2','SILKBOARD');
INSERT INTO DECATH_STORE(STORE_ID,STORE_NAME,STORE_CITY) VALUES(102,'DEC-3','HOSUR');


INSERT INTO DECATH_PRODUCT(PRODUCT_ID,PRODUCT_NAME,PRODUCT_SPORT,PRODUCT_LEVEL,PRODUCT_DESC,ASSOCIATED_STORES) VALUES(200,'BAT','CRICKET','HIGH','OUTDOOR GAME',100);
INSERT INTO DECATH_PRODUCT(PRODUCT_ID,PRODUCT_NAME,PRODUCT_SPORT,PRODUCT_LEVEL,PRODUCT_DESC,ASSOCIATED_STORES) VALUES(201,'BALL','CRICKET','HIGH','OUTDOOR GAME',100);
INSERT INTO DECATH_PRODUCT(PRODUCT_ID,PRODUCT_NAME,PRODUCT_SPORT,PRODUCT_LEVEL,PRODUCT_DESC,ASSOCIATED_STORES) VALUES(202,'RACKET','TENNIS','MODERATE','OUTDOOR GAME',102);